# Generated by Django 5.0 on 2024-01-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pankh', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
