# Generated by Django 5.0 on 2023-12-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_usercourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prerequisite',
            name='course',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='user',
        ),
        migrations.DeleteModel(
            name='Learning',
        ),
        migrations.DeleteModel(
            name='Prerequisite',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='UserCourse',
        ),
    ]
