# Generated by Django 5.0 on 2024-01-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='assignment_file',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='video',
            name='assignment_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
